/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Fasthand_CONSTANTS_H
#define Fasthand_CONSTANTS_H

#include "Fasthand_types.h"

namespace Fasthand {

class FasthandConstants {
 public:
  FasthandConstants();

};

extern const FasthandConstants g_Fasthand_constants;

} // namespace

#endif
