/* 
**  mod_get_request.c -- Apache sample get_request module
**  [Autogenerated via ``apxs -n get_request -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_get_request.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /get_request in as follows:
**
**    #   httpd.conf
**    LoadModule get_request_module modules/mod_get_request.so
**    <Location /get_request>
**    SetHandler get_request
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /get_request and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/get_request 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_get_request.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

static void print_apr_table(request_rec *r, const apr_table_t *t) {
	const apr_array_header_t* array = apr_table_elts(t);
	apr_table_entry_t* elts = (apr_table_entry_t*)array->elts;
	int i;
	for (i = 0; i < array->nelts; i++) {
		ap_rprintf(r, "\t%s : %s\r\n", elts[i].key, elts[i].val);
	}
}

/* The sample content handler */
static int get_request_handler(request_rec *r)
{
    if (strcmp(r->handler, "get_request")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_get_request.c\r\n", r);
	
	ap_rputs("headers_in: \r\n", r);	
	print_apr_table(r, r->headers_in);

	ap_rputs("headers_out: \r\n", r);	
	print_apr_table(r, r->headers_out);

    return OK;
}

static void get_request_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(get_request_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA get_request_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    get_request_register_hooks  /* register hooks                      */
};

