/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef topic_CONSTANTS_H
#define topic_CONSTANTS_H

#include "topic_types.h"

namespace multi { namespace service {

class topicConstants {
 public:
  topicConstants();

};

extern const topicConstants g_topic_constants;

}} // namespace

#endif
